#!/usr/bin/env bash

# Display listening TCP ports
echo "Active Internet connections (only servers)"
netstat -tln | awk '$1 == "tcp" {print $0}'

# Display listening UDP ports
netstat -uln | awk '$1 == "udp" {print $0}'

# Display UNIX domain sockets
echo "Active UNIX domain sockets (only servers)"
netstat -lx | awk '$1 == "unix" {print $0}'
