#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument. Accepts a string as an argument and Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed and Ping the IP 5 times.

# Check if an IP address is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Check if more than one argument is provided
if [ $# -gt 1 ]; then
    echo "Error: Only one argument (the IP address) should be provided."
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 $1
